site_name: flareflareflarestar
site_author: flareflareflarestar

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    # Light mode
    - scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - About: about.md
  - Samples:
      - User Guide: samples/user-guide.md
      - Quickstart Guide: samples/quickstart-rewrite.md
      - Troubleshooting Guide: samples/troubleshooting-guide-rewrite.md
      - API Reference Rewrite: samples/api-reference-rewrite.md
      - Fix Bad Docs: samples/fix-bad-docs.md