site_name: Technical Writing Portfolio
site_author: flareflareflarestar

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.instant
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Samples:
      - Quickstart Guide: samples/quickstart-guide.md
      - Troubleshooting Guide: samples/troubleshooting-guide-rewrite.md
      - Fix Bad Docs: samples/fix-bad-docs.md